POST https://{{host}}/api/v1/system-login
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{system-username}}&password={{system-password}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("auth_token", response.body.access_token);

    client.test("Has access token", function() {
        client.assert(response.body.hasOwnProperty("access_token"), "Cannot find 'access token' option in response");
    });
%}

###
GET https://{{host}}/api/v1/algorithms/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

%}


###
GET https://{{host}}/api/v1/algorithms/{{trading_wallet_address}}/transactions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

%}
